#!/bin/bash
if [ "$(iwconfig 2>/dev/null | grep -Eo "ESSID:off/any")" ]; then
check=no; else
	if [ "$(iwconfig 2>/dev/null | grep -Eo "Link Quality:0")" ]; then
	check=no; else true; fi; fi
res=$(iwconfig 2>/dev/null | grep "Link Quality" | sed -e 's/^[ \t]*//' | cut -d" " -f 2 | cut -d"=" -f 2)
if [ "$check" ]; then echo '0/100'; else echo $res; fi
